name: Build Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Add NuGet Sources
        run: |
          if ! dotnet nuget list source | grep -q "nuget.org"; then
            dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org
          fi
          if ! dotnet nuget list source | grep -q "Dalamud"; then
            dotnet nuget add source https://goatcorp.dev/nuget --name Dalamud
          fi

      - name: Restore Dependencies
        run: dotnet restore --configfile nuget.config

      - name: Build Plugin
        run: dotnet build --configuration Release --framework net7.0

      - name: List Build Directory Contents Before Upload
        run: ls -R bin/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoMountWhileMoving
          path: bin/**
